linters-settings:
  gofmt:
    simplify: false
  govet:
    check-shadowing: true
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to mention the specific linter being suppressed
  gocyclo:
    min-complexity: 20
  goconst:
    ignore-tests: true
  goheader:
    template-path: '.golangci.goheader.template'
    values:
      regexp:
        copyright-year: 20[2-9]\d
  lll:
    line-length: 120
  forbidigo:
    forbid:
      - '^print.*'
      - 'fmt\.Print.*'
    exclude_godoc_examples: false

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - revive
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - importas
    - lll
    - misspell
    - makezero
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck

    # deprecated linters:
    # - varcheck
    # - ifshort
    # - exhaustivestruct
    # - deadcode
    # - structcheck

    # don't enable:
    # - asciicheck
    # - dupl
    # - gochecknoglobals
    # - gocognit
    # - goerr113
    # - maligned
    # - nestif
    # - prealloc
    # - testpackage
    # - wsl
    # - cyclop # not interested in package complexities at the moment

# List of regexps of issue texts to exclude.
issues:
  exclude-rules:
    - path: _test
      linters:
        - varnamelen
        - testpackage
        - nonamedreturns
        - funlen # it can be annoying for table-driven tests
        - dupl
        - goerr113
        - maintidx
    - path: _integration_test
      linters:
        - varnamelen
        - testpackage
        - nonamedreturns
        - funlen # it can be annoying for table-driven tests
        - dupl
        - goerr113
        - maintidx
        - paralleltest # we don't want to run the integration tests in parallel because we want deterministic results
    - path: acceptance_test
      linters:
        - paralleltest
