run:
  timeout: 5m

linters-settings:
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to mention the specific linter being suppressed
  goconst:
    ignore-tests: true
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - (context.Context).Err()
  goheader:
    template-path: '.golangci.goheader.template'
    values:
      regexp:
        copyright-year: 20[2-9]\d
  forbidigo:
    forbid:
      - '^print.*'
      - 'fmt\.Print.*'
    exclude_godoc_examples: false

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - revive
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacebloat
    - importas
    - misspell
    - makezero
    - nakedret
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - rowserrcheck
    - staticcheck
    - stylecheck
    # - sqlclosecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
    - loggercheck
    - mirror
    - musttag
    - nosprintfhostport
    - promlinter
    - reassign
    - testableexamples
    - usestdlibvars
    - zerologlint

    # deprecated linters:
    # - varcheck
    # - ifshort
    # - exhaustivestruct
    # - deadcode
    # - structcheck

    # don't enable:
    # - asciicheck
    # - dupl
    # - gochecknoglobals
    # - gocognit
    # - goerr113
    # - maligned
    # - nestif
    # - prealloc
    # - testpackage
    # - wsl
    # - cyclop # not interested in package complexities at the moment

# List of regexps of issue texts to exclude.
issues:
  exclude-rules:
    - path: _test
      linters:
        - varnamelen
        - testpackage
        - nonamedreturns
        - funlen # it can be annoying for table-driven tests
        - dupl
        - goerr113
        - maintidx
    - path: _integration_test
      linters:
        - varnamelen
        - testpackage
        - nonamedreturns
        - funlen # it can be annoying for table-driven tests
        - dupl
        - goerr113
        - maintidx
        - paralleltest # we don't want to run the integration tests in parallel because we want deterministic results
    - path: acceptance_test
      linters:
        - paralleltest
