version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  settings:
    forbidigo:
      forbid:
        - pattern: ^print.*
        - pattern: fmt\.Print.*
    goheader:
      values:
        regexp:
          copyright-year: 20[2-9]\d
      template-path: .golangci.goheader.template
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - (context.Context).Err()
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - err113
          - funlen
          - maintidx
          - nonamedreturns
          - testpackage
          - varnamelen
        path: _test
      - linters:
          - dupl
          - err113
          - funlen
          - maintidx
          - nonamedreturns
          - paralleltest
          - testpackage
          - varnamelen
        path: _integration_test
      - linters:
          - paralleltest
        path: acceptance_test
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
