// Code generated by MockGen. DO NOT EDIT.
// Source: source.go
//
// Generated by this command:
//
//	mockgen -package mock -source source.go -destination ./mock/source.go
//

// Package mock is a generated GoMock package.
package mock
