// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package config

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigDsn   = "dsn"
	ConfigTable = "table"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigDsn: {
			Default:     "",
			Description: "DSN is the configuration of the data source name to connect to the Amazon Redshift.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigTable: {
			Default:     "",
			Description: "Table is used as the target table into which records are inserted.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
