name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        env:
          REDSHIFT_DSN: ${{ secrets.REDSHIFT_DSN }}
        run: make test GOTEST_FLAGS="-v -count=1"
